# #print ("Twinkle, twinkle, little star,")
# #print ("    How i wonder what you are!")
# #print("         Up above the world so high")
# #print("         Like a diamond in the sky")
# #print ("Twinkle, twinkle, little star,")
# #print ("    How i wonder what you are!")

# #1. STRINGS

# #num1 = int(input("enter first number bitch "))
# #num2 = int(input("enter second number biatch "))

# #equals = num1 * num2
# #print ("the answer is: ", equals)

# #2. INPUTTING MULTIPLICATION

# #print ("Name", "Is", "Gino", sep = '**')

# #SEPARATION

# #num = 458.980890808
# #print ('%.2f' % num)

# #3. NEAREST HUNDREDS

# #numbers = []

# #for i in range (0, 6):
# #    print ("enter decimals numbers", i, ":")
    
# #    item = float(input())
    
# #    numbers.append(item)
# #print (item)

# #4. ALLOW 5 ITEMS

# name = input("what is your name bro? ")
# age = int (input("and how old are you bro? "))
# height = float (input("how tall are you braa? "))

# print ("Hello" +" "+ name )
# print ("oh okay so you are", age, "years old ")
# print ("wow so you are" +" "+ str (height), "cm tall ")

# #5. INPUTTING WITH TYPECASTING (STR, FLOAT, INT)
# note that if you code +" "+ you must include (str) to the variable.

# #count = 0 
# #for numbers in range (1, 20)
# #    if numbers % 2 == 0:
# #    count += 1
# #    print (numbers)
# #print (f"Therefore there is", count, "equal numbers in a 100 digit range")

# #6. FOR LOOP

# #import time

# #for seconds in range (50, 0, -1):
# #    print (seconds)
# #    time.sleep(1)

# #print ("well done")

# #7. FOR LOOPS WITH CS

# #website = "http://google.com"

# #slice = slice(7, -4)
# #print (website[slice])

# #8. SLICING

# # rows = int(input("how many numbers of rows: "))
# # columns = int(input("how many columns: "))
# # symbol = input("what symbol do you want to use? ")

# # for i in range (rows):
# #     for j in range (columns):
# #         print(symbol, end ="")
# #     print()

# #9. NESTED LOOPS

# # def add_numbers(a, b):
# #     sum = a + b
# #     return sum

# # result = add_numbers (7, 90)
# # print(result)

# # ==========================

# # def divisible_number_by_5 (start, end):
# #     count = 0
# #     for number in range (start, end + 1):
# #         if number % 5 == 0:
# #             count += 1
# #             print (number)

# #     return count

# # start = 1
# # end = 100

# # divisible_count = divisible_number_by_5 (start, end)
# # print (f"total numbers that are divisible by 5 is: {divisible_count}")

# #10. RETURN STATEMENT

# # name = "code"

# # def display_name():
# #     name = "code"
# #     print(name)

# # display_name()

# #11. GLOBAL AND LOCAL SCOPE

# # num = input("when iputting a negative number the result turns into a absolute number")
# # num = float(num)
# # num = abs(num)
# # num = round (num)
# # print (num)

# # print (abs(round(float(input("when iputting a negative number the result turns into a absolute number")))))

# #12. NESTED LOOPS

# # def add(*args):
# #     sum = 0
# #     for i in args:
# #         sum += i
# #     return sum

# # print (add(1,2,3,4,5,6,7))

# #13. ARGS (*) PACKING















